# Generated by Django 5.0.1 on 2024-02-01 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SericeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MilitiryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=200, unique=True, verbose_name='MilitaryID')),
                ('expiry_date', models.DateField()),
                ('full_name', models.CharField(max_length=200)),
                ('rank', models.CharField(choices=[('1', 'S1'), ('2', 'S2'), ('3', 'S3')], max_length=100)),
                ('contact', models.CharField(max_length=11)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('licence_plate', models.CharField(blank=True, max_length=6, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Musers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=11)),
                ('militiry_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MilitiryMembers', to='visitors.militirymember')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vusers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate', models.CharField(choices=[('0', 'DockYard'), ('1', 'Naden'), ('2', 'WorkPoint')], max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('returnd', models.BooleanField(default=False)),
                ('issue_time', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date_return', models.DateField(blank=True, null=True)),
                ('time_return', models.TimeField(blank=True, null=True)),
                ('tag_no', models.CharField(default=0, max_length=6)),
                ('gear_no', models.CharField(default=0, max_length=6)),
                ('desination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desinition2', to='visitors.desinition')),
                ('militiry_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MilitiryMembersI', to='visitors.militirymember')),
                ('service_type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='service_t', to='visitors.sericetype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Viusers', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ManyToManyField(related_name='visitors', to='visitors.visitor')),
            ],
        ),
    ]
