# Generated by Django 5.0.1 on 2024-02-02 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='militirymember',
            name='rank',
            field=models.CharField(choices=[('2', 'S2'), ('1', 'S1'), ('3', 'S3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='visit_information',
            name='desination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desinition_d', to='visitors.desinition'),
        ),
        migrations.AlterField(
            model_name='visit_information',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_t', to='visitors.sericetype'),
        ),
        migrations.AlterField(
            model_name='visit_information',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desinition_u', to='visitors.desinition'),
        ),
        migrations.AlterField(
            model_name='visit_information',
            name='tag_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='visitors.tag'),
        ),
    ]
