# Generated by Django 4.2.7 on 2023-12-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit_information',
            name='returnd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visit_information',
            name='gate',
            field=models.CharField(choices=[('0', 'DockYard'), ('1', 'Naden'), ('2', 'WorkPoint')], max_length=200),
        ),
    ]
