# Generated by Django 5.0.1 on 2024-01-31 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SericeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='militirymember',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='militirymember',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='militirymember',
            name='licence_plate',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='militirymember',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit_information',
            name='date_return',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit_information',
            name='gear_no',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='visit_information',
            name='returnd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit_information',
            name='tag_no',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='visit_information',
            name='time_return',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit_information',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Viusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='militirymember',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='militirymember',
            name='member_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='MilitaryID'),
        ),
        migrations.AlterField(
            model_name='militirymember',
            name='rank',
            field=models.CharField(choices=[('2', 'S2'), ('1', 'S1'), ('3', 'S3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='visit_information',
            name='gate',
            field=models.CharField(choices=[('0', 'DockYard'), ('1', 'Naden'), ('2', 'WorkPoint')], max_length=200),
        ),
        migrations.AlterField(
            model_name='visit_information',
            name='issue_time',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='visit_information',
            name='service_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='service_t', to='visitors.sericetype'),
        ),
    ]
