# Generated by Django 5.0.1 on 2024-01-29 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_sericetype_militirymember_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AddField(
            model_name='visit_information',
            name='tag_no',
            field=models.CharField(default=0, max_length=6),
        ),

    ]
