# Generated by Django 4.2.7 on 2023-12-15 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitors', '0002_visit_information_returnd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='militirymember',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Musers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit_information',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Viusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
