# Generated by Django 5.0.1 on 2024-01-29 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_sericetype_militirymember_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        
        
        
        
        migrations.AddField(
            model_name='visit_information',
            name='service_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='service_t', to='visitors.sericetype'),
        ),
        migrations.DeleteModel(
            name='MilitaryBelong',
        ),
    ]
