# Generated by Django 5.0.1 on 2024-01-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_militirymember_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militirymember',
            name='rank',
            field=models.CharField(choices=[('3', 'S3'), ('1', 'S1'), ('2', 'S2')], max_length=100),
        ),
    ]
