# Generated by Django 5.0.1 on 2024-01-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_alter_militirymember_rank'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='militirymember',
            name='rank',
            field=models.CharField(choices=[('2', 'S2'), ('3', 'S3'), ('1', 'S1')], max_length=100),
        ),
        migrations.AlterField(
            model_name='visit_information',
            name='issue_time',
            field=models.DateTimeField(),
        ),
    ]
